source('mma_2weeks-naive.r')
source('mma_2weeks-pvalues.r')
source('mma_months-naive.r')
source('mma_months-pvalues.r')
source('mma_test-naive.r')
source('mma_test-pvalues.r')
source('mma_weeks-naive.r')
source('mma_weeks-pvalues.r')